### PR TITLE
Revise error pages

### PR DESCRIPTION
**Pull request by asahiko**
- Removes email address and point only to the contact page
- Stop embedding image and stylesheet
- Use local font file instead of Google Fonts API
- Automatically show current year for copyright

Closes https://github.com/antleaf/nims-mdr-development/issues/411

### CODE REVIEW

**Comment by nabeta** [comment]
@Steven-Eardley Do you know any convenient way to create a link to the files in the ``app/assets`` directory from a static html file in the ``public`` directory? @asahiko 's PR works, but some files are duplicated.

**Comment by asahiko** [comment]
Completely different from the approach I took, a common strategy appears to be creating a new controller to deal with errors.
- [Custom Error Pages in Ruby on Rails | Web-Crunch](https://web-crunch.com/posts/custom-error-page-ruby-on-rails)
- [Create Custom Error Pages in Rails - Awesome Web Blog](https://anoobbava.github.io/blog/2018/03/22/create-custom-error-pages-in-rails/)

There's also this gem:
- [richpeck/exception_handler](https://github.com/richpeck/exception_handler)

**Comment by Steven-Eardley** [comment]
I think in rails the contents of `app/assets` are written to `public` by the asset pipeline, so references should be as if they're in `public` anyway

**Comment by Steven-Eardley** [comment]
Otherwise, symlinks are effective!

**Comment by nabeta** [comment]
@Steven-Eardley Thanks, we will try a symbolic link first.

**Comment by nabeta** [comment]
Symlinks works as expected.

**Pull request merged**
