### PR TITLE
Update citation page

### PR DESCRIPTION
**Pull request by nabeta**
https://github.com/antleaf/nims-mdr-development/issues/303

- add setup_pub_source and setup_pub_page helper
- display Publication#creator on the citation page

### CODE REVIEW

**Comment by orangewolf** [comment]
@nabeta I feel like I'm missing something, perhaps something obvious, so please forgive me if that is so.  I see the display logic here to take the creator column and parse out the JSON from it, but I do not see any code to write that column.  If that is because you're expecting me to write that part, not problem, I can do so, but again, if I'm missing something I don't want to do work that conflicts with yours.

The presenter and view code does make total sense and appears like it should work once data is in the creator column on the work.

**Comment by nabeta** [comment]
@orangewolf Thank you for your comment. The ``creator`` property we'd like to use comes from the Hyrax basic metadata.
https://github.com/samvera/hyrax/blob/2.x-stable/app/models/concerns/hyrax/basic_metadata.rb#L15
https://github.com/samvera/hyrax/blob/2.x-stable/app/indexers/hyrax/basic_metadata_indexer.rb#L5

I modified ``SolrDocument`` class and Presenter classes to fetch the value of ``creator``, and copied the template file to display it.
https://github.com/antleaf/nims-hyrax/pull/237/files#diff-d2bdd1260f092046630bdeeeccf82803

I think I did almost all of the task, but I should write a test code for the view file to confirm that the ``creator`` property is displayed correctly. I'm not familiar with the Presenter pattern, so any advice will be welcome.

**Comment by orangewolf** [comment]
@nabeta I agree that your display of the information once it is written to the model appears to do what you want it to do for citation display. 

But I do not see it ordering the child objects in other parts of the display based on the separate creator field entry. 

I also do not see where the field is written to in the first place.  To be specific - when a user goes to this form: https://share.getcloudapp.com/YEupG1mx and adds several people, how is the creator field filled in with the order?

**Comment by Steven-Eardley** [comment]
I'm not having much luck with this one - getting internal server errors on the citation page:

```
ActionView::Template::Error (undefined method `[]' for nil:NilClass):
web_1       | F, [2020-06-05T20:58:42.142936 #22] FATAL -- : [b070972f-7b78-44cd-8aef-e468e997d8dd]     3: <span class="citation">
web_1       | [b070972f-7b78-44cd-8aef-e468e997d8dd]     4: <%= @presenter.creator.first %>.
web_1       | [b070972f-7b78-44cd-8aef-e468e997d8dd]     5: "<%= @presenter.title.first %>".
web_1       | [b070972f-7b78-44cd-8aef-e468e997d8dd]     6: <%= setup_pub_source(@presenter) %>
web_1       | [b070972f-7b78-44cd-8aef-e468e997d8dd]     7: (<%= setup_pub_date(@presenter) %>):
web_1       | [b070972f-7b78-44cd-8aef-e468e997d8dd]     8: <%= @presenter.doi.first %>
web_1       | [b070972f-7b78-44cd-8aef-e468e997d8dd]     9: </span>

```

**Comment by nabeta** [comment]
@Steven-Eardley I added another test. Could you try again?
https://github.com/antleaf/nims-hyrax/pull/237/commits/3e022b4716f5410b3cd2ebf656e69fb357b6d600

**Comment by Steven-Eardley** [comment]
No more 500 errors, but nor am I seeing correct citations (using fresh data)

Title is added correctly, no author whether I use Name or Surname and Firstname fields. In addition, empty paretheses are added to the citation when there is no publication date added for the work, (for publications it's optional metadata)

**Pull request merged**
