### PR TITLE
update FITS to 1.3.0

### PR DESCRIPTION
**Pull request by nabeta**
This pull request is about https://github.com/antleaf/nims-mdr-development/issues/133 .

### CODE REVIEW

**Comment by nabeta** [comment]
Is this line still needed?
https://github.com/antleaf/nims-hyrax/pull/76/commits/8c69cf9866118048daafcb630fc4f30ba4678673#diff-4e5e90c6228fd48698d074241c2ba760L119

**Comment by Steven-Eardley** [comment]
@nabeta I believe that line is needed; the setup needs to know where FITS lives. At least, Hyku uses it, so I reckon we keep it.

**Comment by Steven-Eardley** [comment]
We could do away with it if we install FITS to a location without its version in the path, of course. Like Hyku does, as you noted in https://github.com/antleaf/nims-mdr-development/issues/133#issuecomment-502782444

**Comment by Steven-Eardley** [comment]
But it should work as-is, merging.

**Comment by nabeta** [comment]
After this change was merged, ``ngdrdocker build`` failed on Ubuntu 18.04. It still works on CentOS 7.6.

```
$ ngdrdocker build
```
```
Step 13/25 : RUN mkdir -p /fits/     && wget -q https://projects.iq.harvard.edu/files/fits/files/fits-1.3.0.zip -O /fits/fits-1.3.0.zip     && unzip -q /fits/fits-1.3.0.zip -d /fits/fits-1.3.0     && chmod a+x /fits/fits-1.3.0/fits.sh     && rm /fits/fits-1.3.0.zip
 ---> Running in 102a2ec57672
ERROR: Service 'app' failed to build: The command '/bin/sh -c mkdir -p /fits/     && wget -q https://projects.iq.harvard.edu/files/fits/files/fits-1.3.0.zip -O /fits/fits-1.3.0.zip     && unzip -q /fits/fits-1.3.0.zip -d /fits/fits-1.3.0     && chmod a+x /fits/fits-1.3.0/fits.sh     && rm /fits/fits-1.3.0.zip' returned a non-zero code: 4
```

The following change fixed the problem for me.

```
$ git diff hyrax/Dockerfile
diff --git a/hyrax/Dockerfile b/hyrax/Dockerfile
index 7a0477a..f3f2296 100644
--- a/hyrax/Dockerfile
+++ b/hyrax/Dockerfile
@@ -37,7 +37,7 @@ RUN apt-get update -qq && apt-get install -y --no-install-recommends \
     openjdk-8-jre-headless

 RUN mkdir -p /fits/ \
-    && wget -q https://projects.iq.harvard.edu/files/fits/files/fits-1.3.0.zip -O /fits/fits-1.3.0.zip \
+    && wget -q http://projects.iq.harvard.edu/files/fits/files/fits-1.3.0.zip -O /fits/fits-1.3.0.zip \
     && unzip -q /fits/fits-1.3.0.zip -d /fits/fits-1.3.0 \
     && chmod a+x /fits/fits-1.3.0/fits.sh \
     && rm /fits/fits-1.3.0.zip
```

**Pull request merged**
