### PR TITLE
Remove additional set from form for journal

### PR DESCRIPTION
**Pull request by anusharanganathan**
Fixes antleaf/nims-mdr-development#368

See [gist](https://gist.github.com/anusharanganathan/be2f5af531a8f20cbb5257e8221589b6) for class hierarchy

### CODE REVIEW

**Comment by nabeta** [comment]
@anusharanganathan I was not quite sure how to write a test for the modules located under ``app/inputs``, so I added a view spec to check the rendered HTML.

**Comment by anusharanganathan** [comment]
@nabeta good solution. I deleted my broken test. Thank you!

**Comment by anusharanganathan** [comment]
Fixes https://github.com/antleaf/nims-mdr-development/issues/368

**Review by nabeta — APPROVED** [review]

**Comment by nabeta** [comment]
It works as expected. Thank you! @anusharanganathan

**Pull request merged**
